const bhajansData = [
    {
      "title": "Om Jai Jagdish Hare",
      "lyrics": "ॐ जय जगदीश हरे\nस्वामी जय जगदीश\n\nभक्त जनों के संक\nक्षण में दूर करे\n\nॐ जय जगदीश ह\nॐ जय जगदीश ह\n\nस्वामी जय जगदीश\nभक्त ज़नो के संक\n\nक्षण में दूर करे\nॐ जय जगदीश ह\n\nजो ध्यावे फल पावे\nस्वामी दुख बिन से\n\nसुख सम्पति घर\nसुख सम्पति घर\n\nकष्ट मिटे तन का\nॐ जय जगदीश ह\n\nमात पिता तुम मेरे\nशरण गहूं किसकी\n\nस्वामी शरण गहूं\nतुम बिन और ना\n\nतुम बिन और ना\nआस करूँ जिसकी\n\nॐ जय जगदीश ह\n\nतुम पूरण परमात्\nतुम अंतरियामी\n\nस्वामी तुम अंतरिया\nपार ब्रह्म परमे\n\nपार ब्रह्म परमे\nतुम सबके स्वामी\n\nॐ जय जगदीश ह\n\nतुम करुणा के साग\nतुम पालन करता\n\nस्वामी तुम पालन\nमैं मूरख खलकामी\n\nमैं सेवक तुम स्वा\nकृपा करो भर्ता\n\nॐ जय जगदीश ह\n\nतुम हो एक अगोच\nसबके प्राण पति\n\nस्वामी सबके प्राण\nकिस विध मिलु दया\n\nकिस विध मिलु दया\nतुम को मैं कुमति\n\nॐ जय जगदीश ह\n\nदीन बन्धु दुःख ह\nठाकुर तुम मेरे\n\nस्वामी रक्षक तुम\nअपने हाथ उठाओ\n\nअपनी शरण लगाओ\nद्वार पड़ा तेरे\n\nॐ जय जगदीश ह\n\nविषय-विकार मिटाओ\nस्वामी पाप हरो दे\n\nश्रद्धा भक्ति बढ़ा\nश्रद्धा भक्ति बढ़ा\n\nसन्तन की सेवा\nॐ जय जगदीश ह\n\nओम जय जगदीश\nस्वामी जय जगदीश\n\nभक्त ज़नो के संक\nदास ज़नो के संकट\n\nक्षण में दूर करे\nॐ जय जगदीश ह\n\nॐ जय जगदीश ह\nस्वामी जय जगदीश\n\nभक्त ज़नो के संक\nदास जनो के संकट\n\nक्षण में दूर करे\nॐ जय जगदीश हरे" ,
      "youtube_video": "https://www.youtube.com/embed/NE3SWh9_vR4",
      "index": 1
    },
    {
      "title": "Raghupati Raghav Raja Ram",
      "lyrics": "रघुपति राघव राजा राम\nपतित पावन सीता राम\nरघुपति राघव राजा राम\nपतित पावन सीता राम\n\nरघुपति राघव राजा राम\nपतित पावन सीता राम\nरघुपति राघव राजा राम\nपतित पावन सीता राम\n\nसीता राम\nसीता राम\nभज प्यारे तू सीता राम\nसीता राम\n\nभज प्यारे तू सीता राम\nराम\nरघुपति राघव राजा राम\nपतित पावन सीता राम\n\nरघुपति राघव राजा राम\nपतित पावन सीता राम\nईश्वर अल्लाह तेरो नाम\nसबको सन्मति दे भगवान\n\nईश्वर अल्लाह तेरो नाम\nसबको सन्मति दे भगवान\nरघुपति राघव राजा राम\nपतित पावन सीता राम",
      "youtube_video": "https://www.youtube.com/embed/Gtfufkz68KM?si=vzyzw9wHBje4ogDb",
      "index": 2
    },
    {
      "title": "Vaishnav Jan To",
      "lyrics": "वैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\nवैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\nपर दुख्खे उपकार करे तोये मन अभिमान ना आणे रे\nवैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\n\nसकळ लोक मान सहुने वंदे नींदा न करे केनी रे\nवाच काछ मन निश्चळ राखे धन धन जननी तेनी रे\nवैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\nसम दृष्टी ने तृष्णा त्यागी पर स्त्री जेने मात रे\n\nजिह्वा थकी असत्य ना बोले पर धन नव झाली हाथ रे\nवैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\nमोह माया व्यापे नही जेने द्रिढ़ वैराग्य जेना मन मान रे\nराम नाम सुन ताळी लागी सकळ तिरथ तेना तन मान रे\n\nवैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\nवण लोभी ने कपट- रहित छे काम क्रोध निवार्या रे\nभणे नरसैय्यो तेनुन दर्शन कर्ता कुळ एकोतेर तारया रे\nवैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\n\nपर दुख्खे उपकार करे तोये मन अभिमान ना आणे रे\nवैष्णव जन तो तेने कहिये जे पीड़ परायी जाणे रे\n",
      "youtube_video": "https://www.youtube.com/embed/xipue67yfPQ?si=_fvpTchkN7mIOaBN",
      "index": 3
    },
    {
      "title": "Shree Ganeshay Dheemahi",
      "lyrics": "Gananaayakaay ganadevataay ganadhyakshay dhimahi\nGunasharirai gunmanditay guneshanay dhimahi\nGunathithay gunadhishaay gunpravishtaay dhimahi\n\nEkadantay vakratundy gauritanyay dhimahi\nGajeshanay bhalchandray shriganeshy dhimahi\n\nEkadantay vakratundy gauritanyay dhimahi\nGajeshanay bhalchandray shriganeshy dhimahi\n\nGaanachaturaay gaanpranay gaanantaraatmane\nGanotsukay gaanmattay ganotsukamanase\nGurupujitay gurudevataay gurukulasthayine\n\nGuruvikramy guhyapravaraay gurve gungurave\nGurudaityagalchhetre gurudharmasadaradhyay\n\nGuruputraparitratre gurupakhandkhandakay\nGitsarai geetatatvaay gitagotray dhimahi\nGoongulfy gandhmattay gojaypradaay dhimahi\n\nGunathithay gunadhishaay gunpravishtaay dhimahi\nEkadantay vakratundy gauritanyay dhimahi\n\nGajeshanay bhalchandray shriganeshy dhimahi\nEkadantay vakratundy gauritanyay dhimahi\n\nGajeshanay bhalchandray shriganeshy dhimahi\nGranthgitay granthgeyay granthantaraatmane\nGitlinay gitashrayay geetvadyapatwe\nGeyacharitay gayakvaray gandharvapriyakrute\n\nGayakadhinvigrahai gangajalpranyavate\nGauristanandhyay gaurihridayanandanay\nGaurbhanusutay gauriganeshvaraay\nGauripranyay gauripravnaay gaurabhavay dhimahi\n\nGosahasraay govardhanay gopagopay dhimahi\nGunathithay gunadhishaay gunpravishtaay dhimahi\n\nEkadantay vakratundy gauritanyay dhimahi\nGajeshanay bhalchandray shriganeshy dhimahi\n\nEkadantay vakratundy gauritanyay dhimahi\nGajeshanay bhalchandray shriganeshy dhimahi",
      "youtube_video": "https://www.youtube.com/embed/6bL1uM-c9-s?si=5EWDUimoOgplIe6p",
      "index": 4
    },
    {
      "title": "Bhajo Radhe Govind",
      "lyrics": "भजो राधे गोविंदा |\n\nवल्लभ श्रीनाथ भजो राधे गोविंदा\nद्वारिका ना नाथ भजो राधे गोविंदा||1||\n\nपुरी जगन्नाथ भजो राधे गोविंदा\nबद्री विशाल भजो राधे गोविंदा ||2||\n\nरामेश्वर नाथ भजो राधे गोविंदा\nतिरुपति नाथ भजो राधे गोविंदा ||3||\n\nबालाजी नाथ भजो राधे गोविंदा\nपंढरी नाथ भजो राधे गोविंदा ||4||\n\nरुक्ष्मणि ना नाथ भजो राधे गोविंदा\nवृन्दावन नाथ भजो राधे गोविंदा ||5||\n\nगोवर्धन नाथ भजो राधे गोविंदा\nलक्ष्मी ना नाथ भजो राधे गोविंदा ||6||\n\n''जय श्री राधे कृष्णा''",
      "youtube_video": "https://www.youtube.com/embed/hMkzWap0vu0?si=hslAvOa3u8muvrJv",
      "index": 5
    },
    {
      "title": "Mere To Giridhar Gopal",
      "lyrics": "मेरे तो गिरधर गोपाल दूसरो न कोई\n\nमेरे तो गिरधर गोपाल दूसरो न कोई\nजाके सर मोर मुकुट मेरो पति सोई\nमेरे तो गिरधर गोपाल दूसरो न कोई\n\nकोई कहे कारो, कोई कहे गोरो\nकोई कहे कारो, कोई कहे गोरो\nलियोन हे अक्खियां को\nकोई कहे हलकों, कोई कहे भरो\n\nकोई कहे हलकों, कोई कहे भरो\nलियोन हे तराजू टोल\nमेरे तो गिरधर गोपाल दूसरो न कोई\nमेरे तो गिरधर गोपाल दूसरो न कोई\n\nकोई कहे छानी, कोई कहे छावनी\nकोई कहे छावनी\nलियोन हे पचंता टोल\nतन का गहना मैं सब कुछ दिन\n\nतन का गहना, सब कुछ दिन\nदियो है बाजूबंद खोल\nमेरे तो गिरधर गोपाल दूसरो न कोई\nमेरे तो गिरधर गोपाल दूसरो न कोई\n\nजाके सर मोर मुकुट मेरो पति सोई\nमेरे तो गिरधर गोपाल दूसरो न कोई",
      "youtube_video": "https://www.youtube.com/embed/FMtPn6-fjq0?si=1snAUVTl7AM3WN12",
      "index": 6
    },
    {
      "title": "Jai Ambe Gauri",
      "lyrics": "Jai ambe gauri, maiyaa, jai shyama gauri\nTumko nisadin dhyavat\nTumko nisadin dhyavat\nHari, brahma, shivaji, om jai ambe gauri\n\nMaang sindur viraajat, tiko mrigamad ko\n(maiyaa, tiko mrigamad ko)\nUjjwal se do naina\nChandravadan niko (om jai ambe gauri)\n\nKanak samaan kalevar, raktambar raajai\n(maiyaa, raktambar raajai)\nRaktpushp kee maala\nKanthan par sajai (om jai ambe gauri)\n\nKehri vaahan raajat khadg, khappar dhaaree\n(maiyaa, khadg, khappar dhaaree)\nSur, nar, munijan sevat\nTinke dukhahari (om jai ambe gauri)\n\nKaanan kundal shobhit, nasagre moti\n(maiyaa, nasagre moti)\nKotic chandra divakar\nRaajat sam jyoti (om jai ambe gauri)\n\nShumbh-nishumbh bidaare, mahisasur ghaati\n(maiyaa, mahisasur ghaati)\nDhumr vilochan naina\nNisadin madmaati (om jai ambe gauri)\n\nChand-mund sanhaare, shonit beej hare\n(maiyaa, shonit beej hare)\nMadhu-kaitabha dou maare\nSur bhayheen kare (om jai ambe gauri)\n\nBrahmani, rudrani, tum kamala raani\n(maiyaa, tum kamala raani)\nAagam-nigam bakhaani\nTum shiv pataraani (om jai ambe gauri)\n\n64 yogini mangal, nrity karat bhairon\n(maiyaa, nrity karat bhairon)\nBaajat taal, mrudanga\nAur baajat damru (om jai ambe gauri)\n\nTum hee jag kee mata, tum hee ho bhartaa\n(maiyaa, tum hee ho bhartaa)\nBhaktan kee dukh harata\nSukh-sampati karthaa (om jai ambe gauri)\n\nBhujaa chaar ati shobhit, var mudra dhaaree\n(maiyaa, var mudra dhaaree)\nManavaanchit fal pavat\nSevat nar-naaree (om jai ambe gauri)\n\nKanchan thaal viraajat, agar, kapur, baati\n(maiyaa, agar, kapur, baati)\nShri malketu mein raajat\nKoti ratan jyoti (om jai ambe gauri)\n\nMaan ambe jee kee aarti jo koyi nar gavai\n(maiyaa, jo koyi jan gavai)\nKahat shivanand swami\n\"sukh-sampatti paavai\" (om jai ambe gauri)\n\nJai ambe gauri, maiyaa, jai shyama gauri\nTumko nisadin dhyavat\nTumko nisadin dhyavat\nHari, brahma, shivaji, om jai ambe gauri",
      "youtube_video": "https://www.youtube.com/embed/jsYWCRJq3CY?si=YD6LF9fQHDLCNn-V",
      "index": 7
    },
    {
      "title": "Ganpati Bappa Morya",
      "lyrics": "Ganapati Bappa Moraya Pudhachya Varshi Lavkar Ya\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\n\nMere Mann Mandir Mein Tu Bhagwaan Rahein\nMere Dukh Se Tum Kaise Anjaan Rahe\nMere Ghar Mein Kitane Din Mehmaan Rahe\nMere Dukh Se Tum Kaise Anjaan Rahe\n\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\n\nKitani Ummidein Band Jaati Hai Tumase Tum Jab Aate Ho\nAbb Ke Baras Dekhe Kya De Jaate Ho Kya Le Jaate Ho\nKitani Ummidein Band Jaati Hai Tumase Tum Jab Aate Ho\nAbb Ke Baras Dekhe Kya De Jaate Ho Kya Le Jaate Ho\n\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\n\nApane Sab Bhakton Ka Tumako Dhyaan Rahe\nMere Dukh Se Tum Kaise Anjaan Rahe\nMere Mann Mandir Mein Tu Bhagwaan Rahein\nMere Dukh Se Tum Kaise Anjaan Rahe\n\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\n\nAana Jaana Jivan Hai Jo Aaya Kaise Jaaye Na\nKhilane Se Pehale Hi Lekin Phul Koyi Murjhaaye Na\nAana Jaana Jivan Hai Jo Aaya Kaise Jaaye Na\nKhilane Se Pehale Hi Lekin Phul Koyi Murjhaaye Na\n\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\n\nNyaay Anyaay Ki Kuchh Pehchaan Rahe\nMere Dukh Se Tum Kaise Anjaan Rahe\nMere Mann Mandir Mein Tu Bhagwaan Rahein\nMere Dukh Se Tum Kaise Anjaan Rahe\n\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\n\nHo O O O Asuvan Ka Katara Katara Saagar Se Bhi Hai Gehara\nIsamein Dub Na Jaau Main Tumari Jay Jay Gaau Main\nWarna Ke Jab Aaoge Tum Mujhako Na Paaoge\nTumako Kitana Dukh Hoga Ganapati Bappa Moraya\n\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\n\nApani Jaan Ke Badale Apani Jaan Main Arpan Karata Hoon\nAakhari Darshan Karata Hoon Abb Main Visrjan Karata Hoon\n\nGanapati Bappa Moraya, Ganapati Bappa Moraya\nAgale Baras Tu Juldi Aa\n\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa\nGanapati Bappa Moraya Agale Baras Tu Juldi Aa",
      "youtube_video": "https://www.youtube.com/embed/tME7JgcldxU?si=qe5gy9Xi-aqVUZUB",
      "index": 8
    },
    {
      "title": "Jai Santoshi Mata",
      "lyrics": "जय सन्तोषी माता,\nमैया जय सन्तोषी माता ।\nअपने सेवक जन की,\nसुख सम्पति दाता ॥\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nसुन्दर चीर सुनहरी,\nमां धारण कीन्हो ।\nहीरा पन्ना दमके,\nतन श्रृंगार लीन्हो ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nगेरू लाल छटा छबि,\nबदन कमल सोहे ।\nमंद हंसत करुणामयी,\nत्रिभुवन जन मोहे ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nस्वर्ण सिंहासन बैठी,\nचंवर दुरे प्यारे ।\nधूप, दीप, मधु, मेवा,\nभोज धरे न्यारे ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nगुड़ अरु चना परम प्रिय,\nतामें संतोष कियो ।\nसंतोषी कहलाई,\nभक्तन वैभव दियो ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nशुक्रवार प्रिय मानत,\nआज दिवस सोही ।\nभक्त मंडली छाई,\nकथा सुनत मोही ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nमंदिर जग मग ज्योति,\nमंगल ध्वनि छाई ।\nविनय करें हम सेवक,\nचरनन सिर नाई ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nभक्ति भावमय पूजा,\nअंगीकृत कीजै ।\nजो मन बसे हमारे,\nइच्छित फल दीजै ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nदुखी दारिद्री रोगी,\nसंकट मुक्त किए ।\nबहु धन धान्य भरे घर,\nसुख सौभाग्य दिए ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nध्यान धरे जो तेरा,\nवांछित फल पायो ।\nपूजा कथा श्रवण कर,\nघर आनन्द आयो ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nचरण गहे की लज्जा,\nरखियो जगदम्बे ।\nसंकट तू ही निवारे,\nदयामयी अम्बे ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ॥\n\nसन्तोषी माता की आरती,\nजो कोई जन गावे ।\nरिद्धि सिद्धि सुख सम्पति,\nजी भर के पावे ॥\n\nजय सन्तोषी माता,\nमैया जय सन्तोषी माता ।\nअपने सेवक जन की,\nसुख सम्पति दाता ॥",
      "youtube_video": "https://www.youtube.com/embed/2DTf5rXaOJ0?si=Ng94KmliNhKuGLaA",
      "index": 9
    },
    {
      "title": "Om Namah Shivaya",
      "lyrics": "Om Namah Shivaya Om Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Rameshwaraye Shiva Rameshwaraye\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Namah Shivaya Om Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Gangadharaye Shiva Gangadharaye\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Namah Shivaya Om Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Jatadharaye Shiva Jatadharaye\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Namah Shivaya Om Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Someshwaraye Shiva Someshwaraye\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Namah Shivaya Om Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Vishweshvaraye Shiva Vishweshvaraye\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Namah Shivaya Om Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Koteshvaraye Shiva Koteshvaraye\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya\n\nOm Namah Shivaya Om Namah Shivaya\nHar Har Bhole Namah Shivaya\nHar Har Bhole Namah Shivaya",
      "youtube_video": "https://www.youtube.com/embed/WBzeTz_UpQ4?si=LOsUB8HbCg-ZITat",
      "index": 10
    }
  ]

  module.exports = bhajansData;